apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-appone
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /appone
    server: 192.168.161.131
